# Generated by Django 5.2.5 on 2025-08-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="my_email@mail.com", max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(help_text="87777777777", max_length=11, unique=True, verbose_name="Номер телефона"),
        ),
    ]
