# Generated by Django 5.2.5 on 2025-08-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Введите 11 цифр без дополнительных символов.",
                max_length=11,
                unique=True,
                verbose_name="Номер телефона",
            ),
        ),
    ]
