# Generated by Django 5.2.5 on 2025-08-30 16:13

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Введите 11 цифр без дополнительных символов.",
                max_length=11,
                unique=True,
                validators=[users.validators.validate_phone_number],
                verbose_name="Номер телефона",
            ),
        ),
    ]
