# Generated by Django 5.2.5 on 2025-09-01 20:14

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                help_text="Введите 11 цифр без дополнительных символов.",
                max_length=11,
                unique=True,
                validators=[users.validators.validate_phone_number],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
