services:
  web:
    container_name: restaurant_web
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    container_name: restaurant_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web
    env_file:
      - ./.env

  db:
    image: postgres:16
    container_name: restaurant_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U postgres" ]
        interval: 30s
        timeout: 10s
        retries: 5
    env_file:
      - ./.env

volumes:
  postgres_data:
  static_volume: