# Generated by Django 5.2.5 on 2025-08-30 15:24

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=30, verbose_name="Название")),
                ("description", models.CharField(max_length=150, verbose_name="Описание")),
                (
                    "comment",
                    models.CharField(blank=True, max_length=150, null=True, verbose_name="Дополнительные комментарии"),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("seats", models.PositiveSmallIntegerField(verbose_name="Количество мест")),
                ("price", models.IntegerField(verbose_name="Цена бронирования")),
                ("time_open", models.TimeField(default=datetime.time(9, 0), verbose_name="Время начала бронирования")),
                (
                    "time_close",
                    models.TimeField(default=datetime.time(23, 0), verbose_name="Время окончания бронирования"),
                ),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Дополнительные комментарии")),
                ("is_available", models.BooleanField(default=True, verbose_name="Доступен для бронирования")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tables",
                        to="booking.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стол",
                "verbose_name_plural": "Столы",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("success", "Проведена"), ("cancelled", "Отменена")],
                        default=("active", "Активна"),
                        max_length=9,
                        verbose_name="Статус",
                    ),
                ),
                ("people", models.SmallIntegerField(verbose_name="Количество персон")),
                ("date", models.DateTimeField(verbose_name="Дата и время брони")),
                (
                    "duration",
                    models.TimeField(default=datetime.timedelta(seconds=3600), verbose_name="Продолжительность брони"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_bookings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="booking.table",
                        verbose_name="Стол",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
                "ordering": ["status", "date"],
            },
        ),
    ]
