# Generated by Django 5.2.5 on 2025-09-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={"ordering": ["-price"], "verbose_name": "Стол", "verbose_name_plural": "Столы"},
        ),
    ]
