# Generated by Django 5.2.5 on 2025-09-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_table_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["status", "date"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("active", "Активна"), ("success", "Проведена"), ("cancelled", "Отменена")],
                default="active",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
    ]
