# Generated by Django 5.2.5 on 2025-09-02 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_options_alter_booking_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={"ordering": ["date"], "verbose_name": "Бронирование", "verbose_name_plural": "Бронирования"},
        ),
    ]
