# Generated by Django 5.2.5 on 2025-09-05 01:36

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_alter_booking_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[users.validators.validate_phone_number],
                        verbose_name="Номер телефона",
                    ),
                ),
                ("text", models.TextField(verbose_name="Сообщение")),
                ("is_solved", models.BooleanField(default=False, verbose_name="Обработана")),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
    ]
