# Generated by Django 5.2.5 on 2025-09-05 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="created_at",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Дата создания"),
            preserve_default=False,
        ),
    ]
