# Generated by Django 5.2.5 on 2025-09-05 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_feedback_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
    ]
